// Code generated by "stringer -type=Platform"; DO NOT EDIT

package detect

import "fmt"

const _Platform_name = "DESKTOPMOBILEANDROIDIOSWINDOWSPHONE"

var _Platform_index = [...]uint8{0, 7, 13, 20, 23, 35}

func (i Platform) String() string {
	if i >= Platform(len(_Platform_index)-1) {
		return fmt.Sprintf("Platform(%d)", i)
	}
	return _Platform_name[_Platform_index[i]:_Platform_index[i+1]]
}
