// Code generated by "stringer -type=PlatformType"; DO NOT EDIT

package detect

import "fmt"

const (
	_PlatformType_name_0 = "DesktopMobile"
	_PlatformType_name_1 = "Android"
	_PlatformType_name_2 = "IOs"
	_PlatformType_name_3 = "WindowsPhone"
)

var (
	_PlatformType_index_0 = [...]uint8{0, 7, 13}
	_PlatformType_index_1 = [...]uint8{0, 7}
	_PlatformType_index_2 = [...]uint8{0, 3}
	_PlatformType_index_3 = [...]uint8{0, 12}
)

func (i PlatformType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i--
		return _PlatformType_name_0[_PlatformType_index_0[i]:_PlatformType_index_0[i+1]]
	case i == 4:
		return _PlatformType_name_1
	case i == 8:
		return _PlatformType_name_2
	case i == 16:
		return _PlatformType_name_3
	default:
		return fmt.Sprintf("PlatformType(%d)", i)
	}
}
